### ISSUE TITLE
How to write a plugin?

### ISSUE THREAD

**Issue by timeswind** [CroudSupport/vue-quill#1]
For example, I want to show a dialog and let user write math formula in latex and then render those inputs into string, then add the formula back to the editable area

**Comment by BrockReece** [comment]
Hi,

This isn't something I have looked into before, but you will probably be able to write a quill module for this, the best place to start would be the quill documentation
http://quilljs.com/docs/modules/

A word of warning though, I think quill are about to release v1 soon which may introduce breaking changes to the module system.

I hope that helps
