### ISSUE TITLE
None of the icons appear in the toolbar

### ISSUE THREAD

**Issue by roarkmccolgan** [CroudSupport/vue-quill#9]
Hi,

The quill editor is loading however there are no controls in the toolbar.
How do I show the icons/buttons like Bold, Italic, etc?

Thanks!

**Comment by lucidlemon** [comment]
same problem here, have you found anything to solve that?

**Comment by roarkmccolgan** [comment]
Unfortunately not, looking at the source this component seems to be pulling in a much earlier version of quill (0.something, when they are now on 1.1)

I "think" the cdn version of the snow theme has now been updated so none of the classes display as they should.

**Comment by lucidlemon** [comment]
Genius!

Use this CSS and you get the items:

`https://cdnjs.cloudflare.com/ajax/libs/quill/0.20.1/quill.snow.min.css`

**Comment by roarkmccolgan** [comment]
Great! Thanks for investigating. I actually moved on to a standalone editor
CKE Editor but liked quill and the fact that this component existed better
so might revert back

**Comment by BrockReece** [comment]
The change to the readme has been merged in.
Thanks for this, it must have changed since we created the instructions in the readme.

Cheers
Brock
